name: Deploy to Firebase

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm install --legacy-peer-deps
      
    - name: Build
      run: npm run build || ng build --configuration production
      
    - name: Create Firebase config
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-service-account.json
        echo '{"projects":{"default":"${{ secrets.FIREBASE_PROJECT_ID }}"}}' > .firebaserc
        
    - name: Deploy to Firebase
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting --token "$(cat firebase-service-account.json | jq -r .private_key)"
      env:
        GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json