name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --legacy-peer-deps
      
    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Build Angular application
      run: ng build --configuration production
      
    - name: List built files
      run: |
        echo "=== Files in dist/shoplisl-app/ ==="
        ls -la dist/shoplisl-app/
        echo ""
        echo "=== Check if index.html exists ==="
        if [ -f "dist/shoplisl-app/index.html" ]; then
          echo "✅ index.html found!"
          echo "File size: $(wc -c < dist/shoplisl-app/index.html) bytes"
          echo "First 20 lines of index.html:"
          head -20 dist/shoplisl-app/index.html
        else
          echo "❌ index.html NOT found!"
        fi
        echo ""
        echo "=== All files in dist/ ==="
        find dist -type f | head -20
      
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: shoplisl
        channelId: live
    - name: Check browser folder
      run: |
        echo "=== Files in dist/shoplisl-app/browser/ ==="
        ls -la dist/shoplisl-app/browser/
        echo ""
        if [ -f "dist/shoplisl-app/browser/index.html" ]; then
          echo "✅ index.html found in browser folder!"
        else
          echo "❌ index.html still not found!"
        fi